### ISSUE TITLE
Running Ollama tests with the wrong Ollama binary should fail hard

### ISSUE THREAD

**Issue by zimmski** [symflower/eval-dev-quality#156]
I wasted some time to figure out that my Ollama binary was not up to date for the tests. Having a check for that in some "init" function that fails hard if the version is not correct would have made that perfectly clear.

**Comment by bauersimon** [comment]
Just had the same thing happen with Symflower. The only problem is that there is no "global" init function, and tests are run per package. I.e. if we put the version check into one init function (i.e. maybe within the `tools` package) then still all other i.e. `evaluate` tests would fail with cryptic error messages... So instead we have to check for ever test that that needs a tool... I think.
