### ISSUE TITLE
unable to create temporary repository path: exec: WaitDelay expired before I/O complete

### ISSUE THREAD

**Issue by bauersimon** [symflower/eval-dev-quality#219]
Seen this multiple times now...

[unable to create temporary repository path: exec: WaitDelay expired before I/O complete](https://github.com/symflower/eval-dev-quality/blob/4dc1cd069308a2abb5c88b96d6df3ddf14cae23a/docs/reports/multi-run/1run/claude-3.5-sonnet-0/evaluation.log)

**Comment by Munsio** [comment]
Hmmm, I run the commands in docker with screen right one after another, maybe I should have waited a little bit longer after each run.

Anyway I guess it is better if we are able to fix this within the code.

**Comment by bauersimon** [comment]
i saw this a long time ago without docker as well... :thinking:

**Comment by Munsio** [comment]
This should already be fixed with #260 where we move to docker-volumes and #273 where we add a number to the result-directory to make it unique.
