### ISSUE TITLE
Follow-up "Check if the testdata repository is valid before running the evaluation, so it is checked just once"

### ISSUE THREAD

**Issue by ruiAzevedo19** [symflower/eval-dev-quality#266]
I think the language of a repository should come from the repository itself. I.e. either from the path it was created with (if it contains `golang` or `java`)... Or even better it is part of the specification file.

Could you add that as a follow-up refactoring? Not too important right now...

_Originally posted by @bauersimon in https://github.com/symflower/eval-dev-quality/pull/265#discussion_r1677369351_

**Comment by Munsio** [comment]
Already merged, closing this Issue.
