### ISSUE TITLE
"symflower unit-tests" timeout error differs between Linux and Windows

### ISSUE THREAD

**Issue by ruiAzevedo19** [symflower/eval-dev-quality#280]
The error messages from the "symflower unit-tests" timeout differ on Linux and Windows
- Linux: `signal: killed`
- Windows:  it has a weird behavior, sometimes the error is `context.DeadlineExceeded`  other times `exit status 1`

Tests for this can be found in `model/symflower/symflower_test.go:TestModelGenerateTestsForFile`

Workaround: https://github.com/symflower/eval-dev-quality/pull/277

#### TODO
- [ ] Investigate why the errors differ between Linux/Windows
- [ ] Investigate why there are two possible error messages on Windows

**Comment by zimmski** [comment]
Windows and the rest of the world are often different. so i think this is fine. And already implemented with the PR. so closing.
