### ISSUE TITLE
Automatic response categorization

### ISSUE THREAD

**Issue by bauersimon** [symflower/eval-dev-quality#32]
Currently we only parse the first code fence from the response.

Next step is to automatically extract if there was additional information (i.e. explanatory text) by a model.

---

- [x] response with no error
- [x] response not empty
- [x] response with code
- [x] response with no excess (extra content)
- [x] response with extra code -> moved to https://github.com/symflower/eval-dev-quality/issues/44
- [x] categorization

**Comment by zimmski** [comment]
> @zimmski checking if the response contained extra code is not straightforward... we could rudimentary compare the number of functions we expect with what we get as a response and search for signatures there?

FFS GitHub. why don't you have threads?!?!?!?!

Sounds good. Comparing number of functions: you can use `symflower symbols $filePath` for that.  If there is more than one symbol for plain, right?

**Comment by bauersimon** [comment]
> > @zimmski checking if the response contained extra code is not straightforward... we could rudimentary compare the number of functions we expect with what we get as a response and search for signatures there?
> 
> FFS GitHub. why don't you have threads?!?!?!?!
> 
> Sounds good. Comparing number of functions: you can use `symflower symbols $filePath` for that. If there is more than one symbol for plain, right?

Yeah... I would say we always expect as many top-level functions in the tests as the input file had, right? One test per function for now?

**Comment by zimmski** [comment]
> > > @zimmski checking if the response contained extra code is not straightforward... we could rudimentary compare the number of functions we expect with what we get as a response and search for signatures there?
> > 
> > 
> > FFS GitHub. why don't you have threads?!?!?!?!
> > Sounds good. Comparing number of functions: you can use `symflower symbols $filePath` for that. If there is more than one symbol for plain, right?
> 
> Yeah... I would say we always expect as many top-level functions in the tests as the input file had, right? One test per function for now?

That will change right away with the nest use-case: src/gitlab.nethead.at/symflower/symflower/language/golang/testdata/sanity.go

**Comment by zimmski** [comment]
@bauersimon i think `response with extra code` is done? But the issue lacks the categorization task.

**Comment by bauersimon** [comment]
> @bauersimon i think response with extra code is done?

errr no... we don't know what too much code is... we know what extra text is.

Referencing back to https://github.com/symflower/eval-dev-quality/issues/32#issuecomment-2063203055. So we want to use `symflower symbols` to check how many symbols are produced as a result, right? But how do we know how many symbols we should expect? As you mentioned, once we add the sanity check example it's not 1:1 that we want as many tests as there are functions in the test file... right?
