### ISSUE TITLE
Spring Boot "write-test"

### ISSUE THREAD

**Issue by bauersimon** [symflower/eval-dev-quality#365]
- [x] plain test case
- [x] tell LLMs to generate spring boot
- [x] flag results that are not spring boot

---

- https://github.com/symflower/eval-dev-quality/pull/363
- https://github.com/symflower/eval-dev-quality/pull/364
- https://github.com/symflower/eval-dev-quality/pull/367

**Comment by Munsio** [comment]
Related: https://github.com/symflower/eval-dev-quality/pull/367
