### ISSUE TITLE
Fix svg Y axis ticks

### ISSUE THREAD

**Issue by bauersimon** [symflower/eval-dev-quality#73]
![image](https://github.com/symflower/eval-dev-quality/assets/22770887/04d3ca08-47e7-450e-a1ea-94759c265525)

best would be to just delete the axis and label the bars directly

**Comment by bauersimon** [comment]
there is also go echarts but that one only does html export and not svg... looks more mature than the current library though

**Comment by bauersimon** [comment]
Why? For low number of models the labels are fine... Its just for lots of models that the ticks are broken.

**Comment by zimmski** [comment]
Obsolete for sure this time.
