### ISSUE TITLE
Integrate Ollama

### ISSUE THREAD

**Issue by bauersimon** [symflower/eval-dev-quality#91]
We've gotten many requests for Ollama plus [a PR](https://github.com/symflower/eval-dev-quality/pull/27). This would also allow us to run models locally or add new ones that are not yet released.

However, we need to do a few preparations / settle a few questions first before we can do that:
- [x] having multiple providers means we need a mechanic to detect them (cause i.e. people should be able to use ollama without having an openrouter API key)
   - [x] add an `Available` to a provider that checks if it is available/installed/configered with an API key
- [x] i.e. Ollama is a provider that needs to be installed locally. should we handle the installation if one wants to use it?
  - [x] yes cause we need it for testing in the CI
  - [x] same behavior as symflower, i.e. check if it is installed, and install if not 
- [ ] i.e. Ollama is a provider that is running as a background service with an API endpoint... should we make sure it runs?
  - [x] yes
  - [ ] pre-download models
- [x] there are some other parameters to an Ollama provider. I.e. the local IP and/or port it is running on. how can a user configure these?
  - [x] for now assume defaults
- [x] the PR #27 crafts the API requests manually, but Ollama has experimental support for the OpenAI API that we already use with openrouter: https://github.com/ollama/ollama/blob/main/docs/openai.md so use that instead
- [ ] how to integration test Ollama in the CI? is there a "dummy" model that always does the same thing? 
  - https://github.com/ollama/ollama/blob/1b0e6c9c0e5d53aa6110530da0befab7c95d1755/integration/llm_test.go
  - https://github.com/ollama/ollama/issues/4196
- [ ] use random ports for testing to avoid the synchronization of a single Ollama instance

**Comment by bauersimon** [comment]
@zimmski here is what blocked / cost time with this feature
- refactoring things first to improve code reuse (not necessary but worth it IMO)
- spinning up / killing the ollama server in a separate goroutine as background service was not straightforward at all
- had to rebase three times since the early merger is still sitting around #95 and we merged Martin stuff in the meantime
- most "unnecessary time" was spent debugging all the concurrency problems I had with: https://github.com/symflower/eval-dev-quality/commit/89e9efff0227f1976b89793546b31c04c29d3e46
- the fact that we don't have https://github.com/ollama/ollama/issues/4196 so to test Ollama I used the smallest possible model (400MB) where downloading it over and over again for tests always takes a minute each time... making test execution and bug hunting slower... -_-

**Comment by zimmski** [comment]
Moved rest of tasks to #100
