### ISSUE TITLE
Empty responses should not be tested but should fail 

### ISSUE THREAD

**Issue by zimmski** [symflower/eval-dev-quality#92]
See https://github.com/symflower/eval-dev-quality/blob/3e7dc8c5beab65f5958a458a593823ba5c25698e/docs/reports/v0.4.0/openrouter_databricks_dbrx-instruct/java/java/plain.log for an example. You can see that the see that the Java tests are executed even though there is no single character to compile nor execute.

Tasks:
- [x] Return an error if there is an empty response (trim content for whitespaces before checking, that might have been the problem in the first place)
- [x] Result should be that a model that returns an empty response should not receive any additional metrics. There should be a test for that, so we make sure that such a model response never leads to more points. If there is an empty response, it is an almost fail.

**Comment by bauersimon** [comment]
i.e. that means we get rid of the no-empty metric because it will become an error
